### ISSUE TITLE
Angle X Y does not work

### ISSUE THREAD

**Issue by palm369** [Tockn/MPU6050_tockn#1]
Hi, in you example sketches the angle X and Y do not update and are always zero. Only Z updates.

**Comment by wave100** [comment]
Running into the same issue here. Anybody know of a fix?

**Comment by odettman** [comment]
I'm seeing the same thing. What about an alternative library?

**Comment by eitanwass** [comment]
Traced the issue back to the .cpp file where the default values of 0.98f and 0.02f are not passed as acceleration coefficient and gyro coefficient (respectively).
Will update here if I solve the problem.

**Comment by eitanwass** [comment]
FIX:
open the cpp and the h file and change the line accordingly:
on CPP:
`MPU6050::MPU6050(TwoWire &w, float accCoeff, float gyroCoeff){
	wire = &w;
	
	accCoef = accCoeff;
	gyroCoef = gyroCoeff;
}`

O the H:
`MPU6050(TwoWire &w, float accCoeff = 0.98f, float gyroCoeff = 0.02f);`

**Comment by Tockn** [comment]
fixed it.  
Thanks a lot palm369 and eitanwass!
