### ISSUE TITLE
 Why do you need to wait?

### ISSUE THREAD

**Issue by asjdf** [tockn/MPU6050_tockn#19]
Why do you need to wait?
Is this line necessary?

`void MPU6050::calcGyroOffsets(bool console){
	float x = 0, y = 0, z = 0;
	int16_t rx, ry, rz;

	delay(1000);`

I don't quite understand the role of this wait.

**Comment by tockn** [comment]
It is unnecessary, so you can change delay time by new version!
refs: #12
