### ISSUE TITLE
Arduino Fails to upload because of an issue of the library 

### ISSUE THREAD

**Issue by ramithuh** [tockn/MPU6050_tockn#26]
As stated https://stackoverflow.com/a/29135050/2715780
in this answer, 3 '!' marks in a row causes the Mega 2560 bootloader to go into Monitor mode from which it can not finish programming. Therefore the code doesn't upload and causes the error
**stk500v2_ReceiveMessage(): timeout** 

I manually located the .cpp file in my arduino library and changed "done!!!" to "done!", now it uploaded

**Comment by ramithuh** [comment]
<img width="506" alt="Screenshot 2019-04-16 at 8 36 50 PM" src="https://user-images.githubusercontent.com/3503098/56221516-05c31300-6088-11e9-9cf4-e92269c58dd7.png">

**Comment by tockn** [comment]
oh... Thank you for your report. I didn’t know such a specification :(
I will create a patch to fix this issue.

**Comment by ramithuh** [comment]
You're welcome.. Thank you this amazing library! :)

**Comment by tockn** [comment]
Thank you for your PR!
I will merge that!
