### ISSUE TITLE
Value by getangleZ() keeps on increasing with time. Even the sensor is still.

### ISSUE THREAD

**Issue by MuhamdShahab** [tockn/MPU6050_tockn#50]
Hello there,
I have tested the library for MPU6050 on three different sensors. I have faced a common issue where the angle given by getangleZ() kept on increasing after decimals which eventually generates a bigger difference. This is a kind of cumulative error.

**Comment by netpipe** [comment]
drift because of gravity likely there is a mode for extra precision with a gravity factor to fix that iirc.
https://howtomechatronics.com/tutorials/arduino/arduino-and-mpu6050-accelerometer-and-gyroscope-tutorial/
https://forum.arduino.cc/t/removing-gravity-from-mpu6050-data/977167

**Comment by MuhamdShahab** [comment]
For sure gravity val effects the precision  but the noise is cumulative. In case of drift there must b a random behaiviour.

**Comment by MuhamdShahab** [comment]
@tockn ??

**Comment by xuxh-linux** [comment]
Hello, has this problem been solved? I found another problem similar to this problem. When x axis and Y axis obtain a certain Angle value, irregular jump will occur, and the Angle value can reach 600+

**Comment by MuhamdShahab** [comment]
Yes, I have tried to find a solution for this which can be seen in my github repo. 
The other issue which you have mentioned exists. 
I have com to the conculsion that IMU BNO 055 must be used in place of MPU 6050 if you want your orientation angle. For Roll and Pitch only MPU  is fine.
